---
# configure deployment and continuous integration at travis-ci.com

arch: arm64
dist: focal
language: cpp
os: linux

jobs:
  include:

    # Linux_ARM32hf:
    - compiler: arm-linux-gnueabihf-g++-10
      addons:
        apt:
          packages:
            - g++-10-arm-linux-gnueabihf
      script:
        - date
        - arm-linux-gnueabihf-g++-10 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain -Ptarget=Linux_ARM32hf

    # Linux_ARM64 double-precision:
    - compiler: gcc-10
      addons:
        apt:
          packages:
            - g++-10
      script:
        - date
        - aarch64-linux-gnu-g++-10 -E -v
        - travis_wait 20 ./gradlew run build --console=plain -Pflavor=Dp -Ptarget=Linux_ARM64

    # Linux_ARM64 single-precision:
    - compiler: gcc-10
      addons:
        apt:
          packages:
            - g++-10
      script:
        - date
        - aarch64-linux-gnu-g++-10 -E -v
        - travis_wait 20 ./gradlew run build --console=plain -Pflavor=Sp -Ptarget=Linux_ARM64

addons:
  apt:
    update: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
