## catalog of libraries and plugins used to build the jolt-jni project

[versions]

checkstyle = "10.18.0"

[libraries]

junit4 = "junit:junit:4.13.2"
jsnaploader = "io.github.electrostat-lab:snaploader:1.0.0-stable"

[bundles]

[plugins]

analyze = { id = "ca.cutterslade.analyze", version = "1.10.0" }
download = { id = "de.undercouch.download", version = "5.6.0" }