## catalog of libraries and plugins used to build the jolt-jni project

[versions]

[libraries]

junit4 = "junit:junit:4.13.2"

[bundles]

[plugins]

download = { id = "de.undercouch.download", version = "5.6.0" }