## catalog of libraries and plugins used to build the jolt-jni project

[versions]

checkstyle = "10.17.0"

[libraries]

junit4 = "junit:junit:4.13.2"
jsnaploader = "io.github.electrostat-lab:snaploader:1.0.0-delta"

[bundles]

[plugins]

analyze = { id = "ca.cutterslade.analyze", version = "1.9.2" }
download = { id = "de.undercouch.download", version = "5.6.0" }