---
# GitHub Actions workflow for commits pushed to the jolt-jni repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    timeout-minutes: 9
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: gradlew -Pbt=Debug -Pflavor=Sp -Ptarget=Linux64 build install
        run: |
          ./gradlew -Pbt=Debug -Pflavor=Sp -Ptarget=Linux64 build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'

  Java21-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    timeout-minutes: 31
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: g++ --version
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=Linux64 runSmokeTestAll build install
        run: |
          ./gradlew -Ptarget=Linux64 runSmokeTestAll build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux64 -Ptarget=Linux64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux64 -Ptarget=Linux64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-MacOSX64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    timeout-minutes: 40
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=MacOSX64 run runSmokeTestAll build install
        run: |
          ./gradlew -Ptarget=MacOSX64 run runSmokeTestAll build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-MacOSX64 -Ptarget=MacOSX64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-MacOSX64 -Ptarget=MacOSX64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-MacOSX_ARM64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    timeout-minutes: 19
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=MacOSX_ARM64 runSmokeTestAll build install
        run: |
          ./gradlew -Ptarget=MacOSX_ARM64 runSmokeTestAll build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-MacOSX_ARM64 -Ptarget=MacOSX_ARM64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-MacOSX_ARM64 -Ptarget=MacOSX_ARM64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    timeout-minutes: 24
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=Windows64 runSmokeTestAll build install
        run: |
          ./gradlew -Ptarget=Windows64 runSmokeTestAll build install \
             --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
        shell: bash
      - name: gradlew -Partifact=jolt-jni-Windows64 -Ptarget=Windows64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Windows64 -Ptarget=Windows64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'
        shell: bash

  Java21-x-Android_ARM8:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew classes unpackJoltSource unpackTestFramework
        run: |
          ./gradlew classes unpackJoltSource unpackTestFramework \
            --console=plain
      - name: gradlew --build-file=android.gradle -Pflavor=Sp -Ptarget=Android_ARM8 install
        run: |
          ./gradlew --build-file=android.gradle -Pflavor=Sp -Ptarget=Android_ARM8 install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew --build-file=android.gradle -Partifact=jolt-jni-Android_ARM8 -Pflavor=Sp -Ptarget=Android_ARM8 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew --build-file=android.gradle -Partifact=jolt-jni-Android_ARM8 -Pflavor=Sp -Ptarget=Android_ARM8 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-x-Linux_ARM32hf:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    timeout-minutes: 26
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: sudo apt install g++-9-arm-linux-gnueabihf
      - run: arm-linux-gnueabihf-g++-9 --version
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=Linux_ARM32hf assemble
        run: |
          ./gradlew -Ptarget=Linux_ARM32hf assemble \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux_ARM32hf -Ptarget=Linux_ARM32hf clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux_ARM32hf -Ptarget=Linux_ARM32hf clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-x-Linux_ARM64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    timeout-minutes: 32
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: sudo apt install g++-10-aarch64-linux-gnu
      - run: aarch64-linux-gnu-g++-10 --version
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Ptarget=Linux_ARM64 assemble
        run: |
          ./gradlew -Ptarget=Linux_ARM64 assemble \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux_ARM64 -Ptarget=Linux_ARM64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux_ARM64 -Ptarget=Linux_ARM64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java23-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: gradlew -Pbt=Release -Pflavor=Sp -Ptarget=Linux64 build install
        run: |
          ./gradlew -Pbt=Release -Pflavor=Sp -Ptarget=Linux64 build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
