---
# GitHub Actions workflow for commits pushed to the jolt-jni repo - "master" branch

name: CI at GitHub
on:
  # trigger this workflow on pushes and also on pull requests
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: mattsb42/not-grep@master
        with:
          config-file: .github/not-grep.toml
      - run: g++ --version
      - name: gradlew -Ptarget=Linux64 build install
        run: |
          ./gradlew -Ptarget=Linux64 build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux64 -Ptarget=Linux64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux64 -Ptarget=Linux64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java11-x-Linux_ARM32hf:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - run: sudo apt install g++-10-arm-linux-gnueabihf
      - run: arm-linux-gnueabihf-g++-10 --version
      - name: gradlew -Ptarget=Linux_ARM32hf build assemble
        run: |
          ./gradlew -Ptarget=Linux_ARM32hf build assemble \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux_ARM32hf -Ptarget=Linux_ARM32hf clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux_ARM32hf -Ptarget=Linux_ARM32hf clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java11-x-Linux_ARM64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - run: sudo apt install g++-10-aarch64-linux-gnu
      - run: aarch64-linux-gnu-g++-10 --version
      - name: gradlew -Ptarget=Linux_ARM32hf build assemble
        run: |
          ./gradlew -Ptarget=Linux_ARM64 build assemble \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-Linux_ARM64 -Ptarget=Linux_ARM64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Linux_ARM64 -Ptarget=Linux_ARM64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - name: gradlew -Ptarget=MacOSX64 run build install
        run: |
          ./gradlew -Ptarget=MacOSX64 run build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-MacOSX64 -Ptarget=MacOSX64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-MacOSX64 -Ptarget=MacOSX64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
      - name: gradlew -Ptarget=MacOSX_ARM64 build install
        run: |
          ./gradlew -Ptarget=MacOSX_ARM64 build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - name: gradlew -Partifact=jolt-jni-MacOSX_ARM64 -Ptarget=MacOSX_ARM64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-MacOSX_ARM64 -Ptarget=MacOSX_ARM64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - name: gradlew -Ptarget=Windows64 build install
        run: |
          ./gradlew -Ptarget=Windows64 build install \
             --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
        shell: bash
      - name: gradlew -Partifact=jolt-jni-Windows64 -Ptarget=Windows64 clean release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=jolt-jni-Windows64 -Ptarget=Windows64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PossrhPassword='${{ secrets.OSSRH_PASSWORD }}' \
            -PossrhUsername='${{ secrets.OSSRH_USERNAME }}'
        shell: bash

  Java22-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 22
      - uses: actions/checkout@v4
      - name: gradlew -Pflavor=Dp -Ptarget=Linux64 build install
        run: |
          ./gradlew -Pflavor=Dp -Ptarget=Linux64 build install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
